# Import the ansible modules for cisco ACI
- name: Import ACI modules
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - cisco.aci

# Define the APIC URL, username and password
  vars:
    apic_url: "sandboxapicdc.cisco.com"
    apic_user: "admin"
    apic_password: "!v3G@!4@Y"
    epgs: 
        - name: "VLAN-On-Air-Prod_EPG2"
          vlan: "2"
          apn: "PROD_ANP"
          tenant: "PROD"
        - name: "VLAN-On-Air-Prod_EPG3"
          vlan: "3"
          apn: "PROD_ANP"
          tenant: "PROD"
        - name: "VLAN-On-Air-Prod_EPG4"
          vlan: "4"    
          apn: "PROD_ANP"
          tenant: "PROD"
        - name: "VLAN-On-Air-Prod_EPG5"
          vlan: "5"    
          apn: "TEST_ANP"
          tenant: "PROD"
          
# Create a static binding to the interface
  tasks:
    - name: Deploy Static Path binding for given EPG
      cisco.aci.aci_static_binding_to_epg:
        host: "{{ apic_url }}"
        username: "{{ apic_user }}"
        password: "{{ apic_password }}"
        validate_certs: no
        tenant: "{{ item.tenant }}"
        ap: "{{ item.apn }}"
        epg: "{{ item.name }}"
        interface_mode: regular
        interface_type: port_channel
        pod_id: 1
        leafs: 201
        interface: "PC_Ansible_thetechguy"
        encap_id: "{{ item.vlan }}"
        deploy_immediacy: immediate
        state: present
      loop: "{{ epgs }}"