# Import the ansible modules for cisco ACI
- name: Import ACI modules
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - cisco.aci

# Load external credentials
  vars_files:
    - credentials.yml

  tasks:
  - name: Read variables from CSV
    read_csv:
      path: tenant_objects.csv
    register: epg_bd_details

  - name: Loop over CSV content
    include_tasks: tasks/main.yml
    loop: "{{ epg_bd_details.list }}"
    loop_control:
      loop_var: epg_bd_info