- name: Create Bridge Domain
  cisco.aci.aci_bd:
    validate_certs: false
    host: "{{ apic_url }}"
    username: "{{ apic_user }}"
    password: "{{ apic_password }}"
    tenant: "{{ epg_bd_info.tenant }}"
    bd: "{{ epg_bd_info.bd }}"
    vrf: "{{ epg_bd_info.vrf }}"
    enable_routing: "{{ epg_bd_info.enable_routing }}"
    l2_unknown_unicast: flood
    arp_flooding: true
    state: present

- name: Bind Bridge Domain to L3 Out
  cisco.aci.aci_bd_to_l3out:
    validate_certs: false
    host: "{{ apic_url }}"
    username: "{{ apic_user }}"
    password: "{{ apic_password }}"
    bd: "{{ epg_bd_info.bd }}"
    l3out: "{{ epg_bd_info.l3out }}"
    tenant: "{{ epg_bd_info.tenant }}"
    state: present

- name: Create Subnets
  cisco.aci.aci_bd_subnet:
    validate_certs: false
    host: "{{ apic_url }}"
    username: "{{ apic_user }}"
    password: "{{ apic_password }}"
    tenant: "{{ epg_bd_info.tenant }}"
    bd: "{{ epg_bd_info.bd }}"
    gateway: "{{ epg_bd_info.gateway_ip }}"
    mask: "{{ epg_bd_info.gateway_mask }}"
    scope: "{{ epg_bd_info.gateway_scope }}"
    state: present

- name: Create Endpoint Groups
  cisco.aci.aci_epg:
    validate_certs: false
    host: "{{ apic_url }}"
    username: "{{ apic_user }}"
    password: "{{ apic_password }}"
    tenant: "{{ epg_bd_info.tenant }}"
    ap: "{{ epg_bd_info.ap }}"
    epg: "{{ epg_bd_info.epg }}"
    bd: "{{ epg_bd_info.bd }}"
    preferred_group: "{{ epg_bd_info.preferred_group }}"
    state: present
  
- name: Add a new physical domain to EPG binding
  cisco.aci.aci_epg_to_domain:
    validate_certs: false
    host: "{{ apic_url }}"
    username: "{{ apic_user }}"
    password: "{{ apic_password }}"
    tenant: "{{ epg_bd_info.tenant }}"
    ap: "{{ epg_bd_info.ap }}"
    epg: "{{ epg_bd_info.epg }}"
    domain: "{{ epg_bd_info.domain_name }}"
    domain_type: "{{ epg_bd_info.domain_type }}"
    state: present

- name: Add a new contract to EPG binding
  cisco.aci.aci_epg_to_contract:
    validate_certs: false
    host: "{{ apic_url }}"
    username: "{{ apic_user }}"
    password: "{{ apic_password }}"
    tenant: "{{ epg_bd_info.tenant }}"
    ap: "{{ epg_bd_info.ap }}"
    epg: "{{ epg_bd_info.epg }}"
    contract: "{{ epg_bd_info.contract }}"
    contract_type: "{{ epg_bd_info.contract_type }}"
    state: present