- name: Add a new tenant
  cisco.aci.aci_tenant:
    validate_certs: false
    host: "{{ apic_url }}"
    username: "{{ apic_user }}"
    password: "{{ apic_password }}"
    tenant: "{{ tenant_info.tenant }}"
    state: present

- name: Add a new VRF to a tenant
  cisco.aci.aci_vrf:
    validate_certs: false
    host: "{{ apic_url }}"
    username: "{{ apic_user }}"
    password: "{{ apic_password }}"
    tenant: "{{ tenant_info.tenant }}"
    vrf: "{{ tenant_info.vrf }}"
    preferred_group: enabled
    state: present

- name: Add a new AP
  cisco.aci.aci_ap:
    validate_certs: false
    host: "{{ apic_url }}"
    username: "{{ apic_user }}"
    password: "{{ apic_password }}"
    tenant: "{{ tenant_info.tenant }}"
    ap: "{{ tenant_info.ap }}"
    state: present